[project]
name = "langgraph-deep-research-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zaid Nasr", email = "zaidnasr6@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "colorama",
    "langchain",
    "langchain-community",
    "langchain-openai",
    "langchain-tavily",
    "langgraph",
    "langgraph-cli[inmem]",
    "python-dotenv",
]

[project.scripts]
langgraph-deep-research-agent = "langgraph_deep_research_agent:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
